apiVersion: v1
kind: Service
metadata:
  name: kuberadar
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: kuberadar
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kuberadar
            port:
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberadar
  labels:
    app: kuberadar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberadar
  template:
    metadata:
      labels:
        app: kuberadar
    spec:
      containers:
      - name: kuberadar
        image: kuberadar
